# Generated by Django 3.2.13 on 2022-06-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_rename_name_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(db_index=True, default=1, max_length=50),
            preserve_default=False,
        ),
    ]
