# Generated by Django 3.2.13 on 2022-06-12 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_display',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_order',
        ),
    ]
