# Generated by Django 3.2.13 on 2022-06-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20220612_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_display',
            field=models.BooleanField(default=True, verbose_name='Display'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_order',
            field=models.BooleanField(default=True, verbose_name='Order'),
        ),
    ]
