# Generated by Django 3.2.13 on 2022-06-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20220612_2249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_Review',
        ),
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
