# Generated by Django 3.2.13 on 2022-06-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20220615_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='review',
            field=models.TextField(null=True),
        ),
    ]
