# Generated by Django 3.2.13 on 2022-06-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='review',
            field=models.TextField(blank=True),
        ),
    ]
