# Generated by Django 3.2.13 on 2022-06-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(db_index=True, default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
