# Generated by Django 3.2.13 on 2022-06-15 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20220615_1634'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
