# Generated by Django 3.2.13 on 2022-06-19 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_comment_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='slug',
        ),
    ]
