# Generated by Django 3.2.13 on 2022-06-20 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0019_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_good',
            field=models.ManyToManyField(related_name='good_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
