# Generated by Django 3.2.13 on 2022-06-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20220620_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_good',
        ),
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
